### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gunhoflash** [gunhoflash/fe-w45-kanbantodo#1]
- [x] Display column badge
- [x] Show modal
  - [x] Edit column's title
  - [ ] Edit note's title
- [ ] Add test code with [JEST](https://jestjs.io/)
- [x] Keep order of columns and notes
